// export const BACKGROUND_SCREEN_D = '#36d0ff';
export const BACKGROUND_SCREEN_A = '#34c99d';
export const BACKGROUND_SCREEN_B2 = '#daeb5e';
export const BACKGROUND_SCREEN_B3 = '#8b9c0e';
export const BACKGROUND_SCREEN_C2 = 'pink';
export const BACKGROUND_SCREEN_D = '#36d0ff';
export const LEFT_ARROW_ICON_COLOR = '#2452b5';
export const RIGHT_ARROW_ICON_COLOR = '#2452b5';
export const TICK_ICON_COLOR = '#000';
