export const SESSION_ID_KEY = '@SESSION_ID_KEY';
export const R_EXPERIMENTS_KEY = '@R_EXPERIMENTS_KEY';
export const LAST_SCREEN_KEY = '@LAST_SCREEN_KEY';
export const SCREEN_C_VISIBILITY_TIME = 3000;
