export const ALREADY_LAUNCHED_KEY = '@ALREADY_LAUNCHED_KEY';
export const SESSION_ID_KEY = '@SESSION_ID_KEY';
export const R_EXPERIMENTS_KEY = '@R_EXPERIMENTS_KEY';
export const LAST_SCREEN_KEY = '@LAST_SCREEN_KEY';
